grocery=["eggs","ketchep","colock","vimbar","bread",67,20]
print("___________")
print(grocery)
print("___________")
print(grocery[1])
print("___________")
number=[5,4,3,6]
print(number)
print("___________")
print(number[2])
print("___________")
number.sort()
print(number)
print("___________")

number.reverse()
print(number)
print("___________")
print(number[1:4])
print("___________")
print(max(number))
print("___________")
print(min(number))
print("___________")
number=[1,2,3,6]
number.append(7)
print("___________")
print(number)
number=[1,2,3,6]
print(number)

number.insert(1,90)
number.insert(3,99)
print("___________")
print(number)
number=[1,2,3,6]
number.remove(6)
print("___________")
print(number)